[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "This is aproject that has been developed for seeing the crtpto currency by Ai"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "numpy>=2.3.4",
    "pandas>=2.3.3",

]
